### ISSUE TITLE
Refresh errors

### ISSUE THREAD

**Issue by samjam48** [fac18/kgbj-week-7#26]
There are a bunch of errors if you refresh the home page. It looks like you are trying to build the table of house info even though you haven't loaded the result page.

I logged the user in the updateDom() function and it shows that you are trying to add a user to the table and it fails on the first user and doesn't try again.

`{id: 2, name: "Alex", password: "alexandra123", house_id: 2, points: 500}`

This line in index.js should not be lying around in your code if you want this javascript page to be running on index.html. 
`request("/houses", updateDom);`

You should be running it when you are on the right page. So you could put this line in a separate script that is called from the trivia.html page and or just remove index.js script from index.html and only run it on trivia.html.

**Comment by AlexandraOM** [comment]
Thanks!

**Comment by AlexandraOM** [comment]
Thanks!

**Comment by AlexandraOM** [comment]
thanks!
